app = "pocket-planner-api"
primary_region = "gru"

[http_service]
  internal_port = 8080
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[env]
  DATABASE_PATH = "/litefs/pocket-planner.db"
  SECURE_ENV = "true"
  G_CLIENT_IDS = "824653628296-idlah1hdlcjpmeb8310l0ipeo12li5tu.apps.googleusercontent.com"

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"
